[package]
name = "sarimwastaken/roexpress"
version = "0.1.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
t = "osyrisrblx/t@3.0.0"